language: php
php:
  - '7.1'

install:
  - composer self-update
  - composer install --no-interaction

script:
  - vendor/bin/phpunit

before_deploy:
  - curl -L "https://cli.run.pivotal.io/stable?release=linux64-binary&version=6.26.0&source=github-rel" | tar -zx
  - mv cf /usr/local/bin
  - cf --version

deploy:
  skip_cleanup: true
  provider: cloudfoundry
  username: $CF_USER
  password: $CF_PASSWORD
  api: $CF_API
  organization: sandbox
  space: TZHWEDA9